### ISSUE TITLE
Issues connecting to HiveMQ MQTT broker over TLS

### ISSUE THREAD

**Issue by johnnyfleet** [deepcoder/bluetooth-temperature-sensors#12]
Hi there - I've run into a problem trying to use this program with [HiveMQ Cloud](https://www.hivemq.com/downloads/) as the broker.  As part of the standard setup for HiveMQ it expects connections over TLS. This is proving a little challenging for me. 

I've used the following in the `/etc/ble_sensor_mqtt_pub.yaml` config

```yaml
mqtt_server_url: "ssl://<clusterid>.s1.eu.hivemq.cloud:8883"
mqtt_username: "<hivemq_generated_userid>"
mqtt_password: "<hivemq_generated_password>"
```
Note, taken the advice alreadt to switch from tcp:// to ssl//. However when I try and start the service  get the following error in the logs

```
Dec 30 08:17:31 raspberrypi ble_sensor_mqtt_pub[173869]: ble_sensor_mqtt_pub v: 3.0 failed to connect to MQTT server
Dec 30 08:17:31 raspberrypi systemd[1]: ble_sensor_mqtt_pub.service: Main process exited, code=exited, status=1/FAILURE
Dec 30 08:17:31 raspberrypi ble_sensor_mqtt_pub[173869]: Failed to connect to MQTT server, return code -1
```

Doing some googling I found [this stackflow article](https://stackoverflow.com/questions/66559970/how-to-connect-to-hivemq-broker-with-paho-c-library) which suggested making sure I switch to `ssl://` in the url (done) and also adding some ssl options in code. 

I tried to add it in manually in code, by changing `ble_sensor_mqtt_pub.c` from line 560

from
``` C
    // initialize MQTT
    MQTTClient client;
    MQTTClient_connectOptions conn_opts = MQTTClient_connectOptions_initializer;
    MQTTClient_message pubmsg = MQTTClient_message_initializer;
    MQTTClient_deliveryToken token;
```

to 

``` C
    // initialize MQTT
    MQTTClient client;
    MQTTClient_connectOptions conn_opts = MQTTClient_connectOptions_initializer;
    MQTTClient_SSLOptions ssl_opts = MQTTClient_SSLOptions_initializer;
    ssl_opts.enableServerCertAuth = 0;
    conn_opts.ssl = &ssl_opts;
    MQTTClient_message pubmsg = MQTTClient_message_initializer;
    MQTTClient_deliveryToken token;
```

and then `make` and `sudo make install` again but getting the same error. 

Appreciate if there is any advice you can give to set the config right to connect to HiveMQ, or see if there is a way to more gracefully add tls options into the program. 

I don' t know if this is useful either - reference of the [paho c mqtt client from hivemq](https://www.hivemq.com/blog/mqtt-client-library-pahocclient/).

**Comment by deepcoder** [comment]
Apologies, I have not worked with this code in some time. I never did any secure mqtt testing and I don't have a mqtt server with ssl enabled. It looks to be a bit of a pain to setup a self-signed mqtt local server according to 3rd link below. I'm not sure I will have time to do any work on this for a while. A couple thoughts, do you think the client going a mqtt server thru firewall might be an issue? You might see if any of the forks of my repository might have ssl enabled in their code. The 1st two links below discuss using the open mqtt test server at mosquitto.org for testing, you might see if your code can connect to it. Good hunting!

https://test.mosquitto.org/
https://www.eclipse.org/forums/index.php/t/1088757/

http://www.steves-internet-guide.com/mosquitto-tls/

**Comment by johnnyfleet** [comment]
Thanks - I'll see if I can give it a go. I'm not especially proficient in c so if I can get the gist of it working I'll see if I can submit a pull request to review, but likely would need some formatting and adding logic to work only when required.

**Comment by johnnyfleet** [comment]
I'll close this for now @deepcoder. I ended up switching to the local mosquito hosted instance in homeassistant. This seems to be working well so far now.
